### ISSUE TITLE
script seems to work ok, but doesn't actually scrub anything.

### ISSUE THREAD

**Issue by ohnonot** [ssokolow/gtk-recent-scrubber#6]
so i add a path, like this:

```
./gtk_cleanup.py --add /some/path
```

and the .conf file is created in ~/.local/share.
i then run

```
./gtk_cleanup.py -vv --once
```

and get the confirmation "INFO: Removing 173 entries".  
**but ~/.local/share/recently-used.xbel never changes, the entries with the path in question are still there.**

if i run

```
./gtk_cleanup.py --purge
```

it simply empties the whole file.

this is happening on archlinux, btw, and i don't see any other errors when running the script from a terminal.

what gives?  
i'm looking at the source code now, but i'm not versed in python.

**Comment by ssokolow** [comment]
I'm currently tied up with the tail end of my degree project and won't have any meaningful amount of time until May 1st, but I'll do what I can to quickly advise you.

First, `--purge` is acting exactly as it's supposed to. I probably should have called it `--flush` or `--empty` instead.

As for `-vv --once`, the first thing we need to do is confirm that your prefixes are matching the paths you think they are.  

Temporarily make the debugging messages more helpful but less secure by changing this...

``` python
        if found:
            log.info("Removing %d entries", len(found))
            while found:
                try:
                    recent_manager.remove_item(found.pop())
                except gobject.GError:
                    log.warning("Failed to remove item. (Maybe already done)")
```

... into this ...

``` python
        if found:
            log.info("Removing %d entries", len(found))
            manager_fname = manager.get_property('filename')
            while found:
                found_path = found.pop()
                log.debug("Removing %s from %s", found_path, manager_fname)
                try:
                    recent_manager.remove_item(found_path)
                except gobject.GError:
                    log.warning("Failed to remove item. (Maybe already done)")
```

If that says that it's removing the files you want, then my next hypothesis would be that something about your system has broken the ability of GTK+ 2.x apps to manipulate the recent files list, since, if you get the right thing from those debug messages, then `GtkRecentManager.remove_item()` is failing to do its job as documented. (In which case, I'll have to look at it after my degree project is over.)

**Comment by ssokolow** [comment]
...or I messed up in implementing `--once`. If you do get the right names but they're not going away, try running it without `--once` to see if they go away while it's resident.

If so, then I know I need to work harder to force PyGTK to process pending actions before it quits. (I use it every day, but I never personally use `--once`, so it's possible a bug crept in.)

**Comment by ohnonot** [comment]
the code addition results in an error:

```
Traceback (most recent call last):
  File "./gtk_cleanup.py", line 332, in <module>
    main()
  File "./gtk_cleanup.py", line 323, in main
    scrubber.start()
  File "./gtk_cleanup.py", line 236, in start
    self.attach(display_manager, display)
  File "./gtk_cleanup.py", line 202, in attach
    self.scrub(manager)
  File "./gtk_cleanup.py", line 254, in scrub
    manager_fname = manager.get_property('filename')
NameError: global name 'manager' is not defined
```

this is after the usual output (Skipped..... INFO: Removing 39 entries) and identical non-behavior as described.  
but due to that error, i guess, i can't make the script resident.

reverting to the original code, it is just as you said:  
when running resident, the script behaves correctly.

however, i have no need for it to be resident, running it once at login is totally sufficient for me.
